/*
 * Generates datamap.gen.js — a STATIC manifest of the ~28 engine data modules
 * (base + champions mod + text + config/formats) so the browser bundle can load
 * data without the engine's Node-only dynamic require / fs.readdirSync.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.resolve(__dirname, '..', '..', 'pokemon-showdown', 'dist');

const base = ['abilities','rulesets','formats-data','items','learnsets','moves','natures','pokedex','pokemongo','scripts','conditions','typechart','aliases','tags'];
const text = ['pokedex','moves','abilities','items','default'];
const champ = ['abilities','conditions','formats-data','items','learnsets','moves','rulesets','scripts'];
const entries = [];
const add = (key, abs) => { if (fs.existsSync(abs)) entries.push([key, abs]); else console.error('MISSING', abs); };
base.forEach(f => add('data/' + f, `${DIST}/data/${f}.js`));
text.forEach(f => add('data/text/' + f, `${DIST}/data/text/${f}.js`));
champ.forEach(f => add('data/mods/champions/' + f, `${DIST}/data/mods/champions/${f}.js`));
add('config/formats', `${DIST}/config/formats.js`);

let out = '// AUTO-GENERATED by gen-datamap.mjs — do not edit\nconst M = {};\n';
entries.forEach(([k, abs]) => { out += `M[${JSON.stringify(k)}] = require(${JSON.stringify(abs)});\n`; });
out += `
// keep only Champions formats so the loader never requires an unbundled mod
{
  const cf = M['config/formats'];
  if (cf && Array.isArray(cf.Formats)) M['config/formats'] = Object.assign({}, cf, { Formats: cf.Formats.filter(e => e && e.mod === 'champions') });
}
function norm(p){ p=String(p).replace(/\\\\/g,'/').replace(/\\.js$/,''); const m=p.match(/\\/(data|config)\\/(.*)$/); return m?(m[1]+'/'+m[2]):p; }
function psRequire(p){ const k=norm(p); if(k in M) return M[k]; const e=new Error('Cannot find module '+p+' ('+k+')'); e.code='MODULE_NOT_FOUND'; throw e; }
function psReaddirMods(){ return ['champions']; }
module.exports={psRequire,psReaddirMods,__map:M};
`;
fs.writeFileSync(path.join(__dirname, 'datamap.gen.js'), out);
console.log('datamap.gen.js written with', entries.length, 'modules');
